language: node_js
node_js: node
deploy: gentle-citadel-57030
  provider: heroku
  api_key:
    secure: Q5m6lGMnNxzDt08QXMhBy4kfbcG/Uw8k3c6BcV7qqQTiDa7kycJyXl1/rvet3GKbe67/17ZS6wUEHPZybSYTG446wllsUaGuSowJnIYTU+PcndU5C7S7rvP/EwmaT3UUKirPW7B3zyMbkNt6x5mUK+JBOAIR4KldP9on6YYjqaFk7hULYErRhjzJvhoHnXh6WCBjQbV+pIYnoYQQEqX/f5euIBPMEJvxvx8WBqXTXcE+38IMx3D0rktisFbmk57k0XosIrn5aOV4OhcbD64Mku/6cEFiAe1NNh8sDDTCO+090bYtEXTedbpB3sLS5+pd8BstphJy4TKDpWtl5s+oI5DYlbsBESkoORDmnp8d/zCgDmSvnESueV/cxbX6TKumnzMzqdTC0o9EcCFMEc+62bF54JoxzrEfQHrIAnbEkSkN2NKmChQbo4uQyjsEWb0bm9yy5eKUcBmRHpdfH6VOfr4DYf2c20Kl3qSW9g5bxRPNNpf4aGKJgYcUy4WUpCl0XvcpocOUN2cS+5b8WeLlA/ic3ZbXmhjQp8zaDLOHZ74LVECvm4/mqeOQRrvctUoDvYL9gLxbHfKzojNwekdoRH8lN7Wf5GBp1vnBgffhYoNz6WZnpBbNfUH4TuP+qHko1dfeTbE5VsW1H4F3f/r8KE88JjzJHFqwRZ0mbNBO1yU=
  app: node-shopping-list-integration-tests2
  on:
    repo: markedelman/node-shopping-list-integration-tests2
